language: cpp
compiler:
    - clang++-3.7
install:
    - ./waf distclean configure build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
script:
    - build/sw ACGTT ACCGT -m 2 -M 1
